AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FII - Factor Impact Intelligence Backend

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  ClaudeApiKeyArn:
    Type: String
    Description: ARN of the Secrets Manager secret for Claude API key
  FredApiKeyArn:
    Type: String
    Description: ARN of the Secrets Manager secret for FRED API key
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID for Cognito
  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret for Cognito
    NoEcho: true
  AppleTeamId:
    Type: String
    Description: Apple Developer Team ID
    Default: ''
  AppleKeyId:
    Type: String
    Description: Apple Sign-In Key ID
    Default: ''
  ApplePrivateKey:
    Type: String
    Description: Apple Sign-In Private Key
    NoEcho: true
    Default: ''
  ExistingTableName:
    Type: String
    Default: 'fii-table'
    Description: Name of existing DynamoDB table (leave empty to create new)
  ExistingBucketName:
    Type: String
    Default: 'fii-data-dev'
    Description: Name of existing S3 bucket (leave empty to create new)

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 1024
    Timeout: 120
    Environment:
      Variables:
        STAGE: !Ref Stage
        TABLE_NAME: !If [CreateTable, !Ref FiiTable, !Ref ExistingTableName]
        BUCKET_NAME: !If [CreateBucket, !Ref FiiDataBucket, !Ref ExistingBucketName]
        CLAUDE_API_KEY_ARN: !Ref ClaudeApiKeyArn
        FRED_API_KEY_ARN: !Ref FredApiKeyArn
    Layers:
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python312:16
      - !Ref SharedLayer

Resources:
  # ─── Cognito ───

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub fii-user-pool-${Stage}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: name
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: openid profile email
      AttributeMapping:
        email: email
        name: name
        username: sub

  AppleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasAppleConfig
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ProviderName: SignInWithApple
      ProviderType: SignInWithApple
      ProviderDetails:
        client_id: !Sub com.fii.app
        team_id: !Ref AppleTeamId
        key_id: !Ref AppleKeyId
        private_key: !Ref ApplePrivateKey
        authorize_scopes: email name
      AttributeMapping:
        email: email
        name: name
        username: sub

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - GoogleIdentityProvider
    Properties:
      ClientName: !Sub fii-app-client-${Stage}
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - Google
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - profile
        - email
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - fii://callback
        - exp://127.0.0.1:8081/--/callback
      LogoutURLs:
        - fii://signout
      PreventUserExistenceErrors: ENABLED

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: !Sub fii-auth-${Stage}

  # ─── API Gateway ───

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Authorization
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            AuthorizationScopes:
              - openid
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
              audience:
                - !Ref CognitoUserPoolClient

  # ─── DynamoDB ───

  FiiTable:
    Type: AWS::DynamoDB::Table
    Condition: CreateTable
    Properties:
      TableName: !Sub fii-table-${Stage}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # ─── S3 ───

  FiiDataBucket:
    Type: AWS::S3::Bucket
    Condition: CreateBucket
    Properties:
      BucketName: !Sub fii-data-${Stage}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ─── Shared Lambda Layer ───

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub fii-shared-${Stage}
      Description: >-
        Shared utilities (anthropic, fredapi, yfinance, edgartools, pydantic)
        and Python modules. numpy/pandas provided by AWSSDKPandas layer.
      ContentUri: shared_layer/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12
      BuildArchitecture: x86_64

  # ─── Lambda Functions ───

  ApiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub fii-api-handler-${Stage}
      Handler: handler.lambda_handler
      CodeUri: functions/api_handler/
      Description: Main API router for FII
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !If [CreateTable, !Ref FiiTable, !Ref ExistingTableName]
        - S3CrudPolicy:
            BucketName: !If [CreateBucket, !Ref FiiDataBucket, !Ref ExistingBucketName]
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref ClaudeApiKeyArn

  SignalEngineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub fii-signal-engine-${Stage}
      Handler: handler.lambda_handler
      CodeUri: functions/signal_engine/
      Description: FII 6-factor signal analysis engine
      Timeout: 300
      MemorySize: 2048
      Events:
        DailySignalRun:
          Type: Schedule
          Properties:
            Schedule: cron(0 11 ? * MON-FRI *)
            Description: Run signal engine at 6AM ET weekdays
            Enabled: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !If [CreateTable, !Ref FiiTable, !Ref ExistingTableName]
        - S3CrudPolicy:
            BucketName: !If [CreateBucket, !Ref FiiDataBucket, !Ref ExistingBucketName]
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref ClaudeApiKeyArn
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref FredApiKeyArn

  FeedCompilerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub fii-feed-compiler-${Stage}
      Handler: handler.lambda_handler
      CodeUri: functions/feed_compiler/
      Description: Compiles daily feed from signals
      Events:
        DailyFeedCompile:
          Type: Schedule
          Properties:
            Schedule: cron(30 11 ? * MON-FRI *)
            Description: Compile feed at 6:30AM ET weekdays
            Enabled: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !If [CreateTable, !Ref FiiTable, !Ref ExistingTableName]
        - S3CrudPolicy:
            BucketName: !If [CreateBucket, !Ref FiiDataBucket, !Ref ExistingBucketName]

  # NOTE: StrategyEngineFunction requires scipy for portfolio optimization (Prompt 5).
  # scipy will be added as a separate layer when that feature is implemented.
  StrategyEngineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub fii-strategy-engine-${Stage}
      Handler: handler.lambda_handler
      CodeUri: functions/strategy_engine/
      Description: Sharpe optimization and Monte Carlo simulation
      Timeout: 300
      MemorySize: 2048
      Events:
        Optimize:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /strategy/{proxy+}
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !If [CreateTable, !Ref FiiTable, !Ref ExistingTableName]
        - S3CrudPolicy:
            BucketName: !If [CreateBucket, !Ref FiiDataBucket, !Ref ExistingBucketName]

Conditions:
  HasAppleConfig: !Not [!Equals [!Ref AppleTeamId, '']]
  CreateTable: !Equals [!Ref ExistingTableName, '']
  CreateBucket: !Equals [!Ref ExistingBucketName, '']

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
  TableName:
    Description: DynamoDB Table Name
    Value: !If [CreateTable, !Ref FiiTable, !Ref ExistingTableName]
  BucketName:
    Description: S3 Data Bucket Name
    Value: !If [CreateBucket, !Ref FiiDataBucket, !Ref ExistingBucketName]
